# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hello, Nice to Meet you!
email: avc8@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  Data Science | Web Development | DevOps
baseurl: "startbootstrap-freelancer-jekyll" # the subpath of your site, e.g. /blog
url: "http://avantichande.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: SBootstrap
github_username:  avantichande
facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: 4231 12th Ave NE
address_city: Seattle
address_state: WA
address_zip: 98105

# Build settings
markdown: kramdown
